/*
 * This source file was generated by the Gradle 'init' task
 */
package org.gametools.cleaner;

import java.nio.file.Path;

public class App {

    private static final String DEFAULT_INSTALLATION = ".local/share/Steam";

    public static void main(String[] args) {
        String homePath = System.getProperty("user.home");
        Path defaultInstallation = Path.of(homePath).resolve(DEFAULT_INSTALLATION);
        // TODO
    }
}
