name: Build main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Gradle build
        run: ./gradlew test --no-daemon
  build-native:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '23.0.1'
          distribution: 'graalvm-community'
      - name: Gradle native test
        run: ./gradlew nativeTest --no-daemon
      - name: Gradle native test
        run: ./gradlew :steam-cleaner:nativeCompile --no-daemon
