name: Build main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
      - name: Gradle build
        run: ./gradlew test --no-daemon
      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        if: always()
        with:
          name: steam-cleaner-reports
          path: steam-cleaner/build/reports/*
  build-native:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25.0.1'
          distribution: 'graalvm-community'
      - name: Gradle native test
        run: ./gradlew nativeTest --no-daemon
      - name: Gradle native test
        run: ./gradlew :steam-cleaner:nativeCompile --no-daemon
      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        if: always()
        with:
          name: steam-cleaner-reports-native
          path: steam-cleaner/build/reports/*
